<div class="container-fluid pt15 pb15">

    <h2 class="light-grey mt10 mb0 narrow-spaced uppercase normal"><i class="fa fa-lock fa-2x"></i> Ganti Password</h2>

    <nav class="navbar alt navbar-default">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="/setting/general">Setting Umum</a></li>
                <li class="active"><a href="#" onclick="return false;">Ganti Password</a></li>
                <li><a href="/user">User &amp; Grup</a></li>
                <li><a href="/index/help">Support &amp; Bantuan</a></li>
            </ul>
        </div>
    </nav>

    <div class="pl20 pr20">
        <div class="row">
            <div class="col-xs-12">

                <?= $this->message() ?>
                <?= $this->flash() ?>

                <form action="" method="post" class="form-horizontal grey">

                    <div class="row">
                        <div class="col-md-7">

                            <div class="alert alert-info alt">
                                <i class="fa fa-warning"></i> Kombinasi huruf besar,
                                kecil, angka &amp; simbol akan menghasilkan password yang lebih kuat.
                            </div>

                            <?= $this->form($this->changePasswordForm, 'horizontal') ?>

                            <div class="form-group text-right pr15">
                                <button type="submit" class="btn alt green"> <i class="fa fa-save"></i> Simpan </button>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

</div>