<?php

use Stokq\Entity\Account;

/** @var Account $account */
$account = $this->account;

?>

<div class="container-fluid pt15 pb15">

    <h2 class="light-grey mt10 mb0 narrow-spaced uppercase normal"><i class="fa fa-line-chart fa-2x"></i> Penjualan &amp; Belanja</h2>

    <hr/>

    <div class="row">
        <div class="content clearfix">

            <div class="col-xs-12">
                <div class="line-chart-container">
                    <h2 class="m0 mb3 narrow-spaced uppercase normal strong dark-grey">Penjualan &amp; Belanja / Bulan</h2>
                    <span class="grey mb10 block">Dalam 6 bulan terakhir</span>
                    <div id="sales-purchases-monthly" class="line-chart" style="min-height: 380px;"></div>
                </div>
            </div>

        </div>
    </div>

    <h2 class="light-grey mt20 mb0 narrow-spaced uppercase normal"><i class="fa fa-pie-chart fa-2x"></i> Perbandingan Gross</h2>

    <hr/>

    <div class="row">
        <div class="content clearfix">

            <div class="col-xs-12">
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <td>Menu</td>
                        <td>Harga Default</td>
                        <td>Harga Bahan</td>
                        <td>Gross</td>
                        <td style="width: 200px;">%</td>
                    </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($this->grossRatioData as $row) { ?>

                        <tr>
                            <td>
                                <a href="/menu/detail?id=<?= $row['id'] ?>" class="green"><?= $row['name'] ?></a>
                            </td>
                            <td class="text-right">
                                <strong class="grey left">
                                    <?= $this->account->getDefaultCurrency() ?>
                                </strong>
                                <?= number_format($row['default_price'], 2) ?>
                            </td>
                            <td class="text-right">
                                <strong class="grey left">
                                    <?= $this->account->getDefaultCurrency() ?>
                                </strong>
                                <?= number_format($row['qty_price'], 2) ?>
                            </td>
                            <td class="text-right">
                                <strong class="grey left">
                                    <?= $this->account->getDefaultCurrency() ?>
                                </strong>
                                <?= number_format($row['default_price'] - $row['qty_price'], 2) ?>
                            </td>
                            <td>
                                <?php if ($row['default_price'] > 0 && $row['qty_price'] > 0) { ?>
                                    <strong class="grey block">
                                        <?= number_format(100 - ($row['qty_price'] / $row['default_price'] * 100), 2) ?>%
                                    </strong>
                                    <div class="bg-green" style="width: <?= 100 - ($row['qty_price'] / $row['default_price'] * 100) ?>%; height: 10px;"></div>
                                <?php } ?>
                            </td>
                        </tr>

                    <?php } ?>

                    </tbody>
                </table>
            </div>

        </div>
    </div>

</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="/js/chart.js"></script>
<script type="text/javascript">

    google.load('visualization', '1.1', {
        packages: ['corechart', 'bar', 'line'],
        language: '<?= $account->getDefaultLocale() ?>'
    });

    GoogleOnLoadCallback(function() {

        var numberFormatter = NumberFormatter({ format: '#,###', prefix: '<?= $account->getDefaultCurrency() ?> ' }),
            salesAndPurchaseDataDT = ArrayToDataTable(<?= json_encode($this->salesAndPurchaseData) ?>);

        numberFormatter.format(salesAndPurchaseDataDT, 1);
        numberFormatter.format(salesAndPurchaseDataDT, 2);

        new AreaChart().data(salesAndPurchaseDataDT).draw('sales-purchases-monthly');
    });

</script>