<div class="panel-group" role="tablist" aria-multiselectable="true" id="user-accordion">
    <div class="panel panel-default">
        <div class="panel-heading" role="tab">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#user-accordion" href="#add-form-panel" aria-expanded="false" aria-controls="add-form-panel" class="collapsed">
                    <i class="fa fa-plus-circle"></i> Tambah User
                </a>
            </h4>
        </div>
        <div id="add-form-panel" class="panel-collapse collapse in" role="tabpanel" aria-expanded="false">
            <div class="panel-body">

                <form action="/user/create" method="post" role="form" id="add-user-form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Nama</label>
                                <input type="text" name="name" value="" class="form-control" placeholder="Nama">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Email</label>
                                <input type="email" name="email" value="" class="form-control" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Kontak/Telp.</label>
                                <input type="text" name="contact_no" value="" class="form-control" placeholder="Kontak/Telp.">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label">Alamat</label>
                                <textarea name="address" rows="3" class="form-control" placeholder="Alamat"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="form-group mb0 block text-right">
                        <button type="submit" class="btn alt green"><i class="fa fa-save"></i> Simpan</button>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>