<?php

use Stokq\Entity\Account;

/** @var Account $account */
$account = $this->account;

?>

<div class="container-fluid pt15 pb15">

    <h2 class="light-grey mt10 mb0 narrow-spaced uppercase normal"><i class="fa fa-line-chart fa-2x"></i> Statistik Belanja</h2>

    <hr/>

    <div class="row">
        <div class="col-xs-12">
            <div class="line-chart-container">
                <h2 class="m0 mb3 narrow-spaced uppercase normal strong dark-grey">Total Belanja / Bulan</h2>
                <span class="grey mb10 block">Dalam 6 bulan terakhir</span>
                <div id="total-purchased-monthly" class="line-chart" style="min-height: 380px;"></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="line-chart-container">
                <h2 class="m0 mb3 narrow-spaced uppercase normal strong dark-grey">Total Belanja / Warehouse</h2>
                <span class="grey mb10 block">Dalam 6 bulan terakhir</span>
                <div id="purchases-by-warehouse" class="bar-chart"></div>
            </div>
        </div>
    </div>

</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="/js/chart.js"></script>
<script type="text/javascript">

    google.load('visualization', '1.1', {
        packages: ['corechart', 'bar', 'line'],
        language: '<?= $account->getDefaultLocale() ?>'
    });

    GoogleOnLoadCallback(function() {

        var numberFormatter = NumberFormatter({ format: '#,###', prefix: '<?= $account->getDefaultCurrency() ?> ' }),
            totalPurchaseByWarehouseDT = ArrayToDataTable(<?= json_encode($this->totalPurchaseByWarehouse) ?>),
            totalPurchasePerMonthDT = ArrayToDataTable(<?= json_encode($this->totalPurchasePerMonth) ?>);

        numberFormatter.format(totalPurchasePerMonthDT, 1);

        new LineChart().data(totalPurchasePerMonthDT).draw('total-purchased-monthly');
        new MaterialBarChart().data(totalPurchaseByWarehouseDT).draw('purchases-by-warehouse');
    });

</script>