<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="shortcut icon" type="image/png" href="/img/favicon.png">
    <title>StokQ - Manajemen Bahan Makanan, Penjualan, dan Belanja</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php include 'partials/css.phtml' ?>
    <?php include 'partials/js.phtml' ?>

</head>
<body>

<div id="main-window">
    <nav id="main-menu">
        <header>
            <h1>stokQ</h1>
            <a href="#" class="logout-link" id="logout-link">
                <i class="fa fa-lock"></i> logout
            </a>
        </header>
        <ul>
            <?= $this->nav('sidebar_nav') ?>
        </ul>
    </nav>
    <div id="main-container">
        <?= $content ?>
    </div>
</div>

<script>
    $('#logout-link').on('click', function(e) {
        e.stopPropagation();
        e.preventDefault();

        if (confirm('Logout sekarang?')) {
            $('<form action="/access/logout" method="post">').trigger('submit');
        }

        return false;
    });
</script>

</body>
</html>