<?php if (!$this->config()->isDebug()) { ?>

    <link rel="stylesheet" type="text/css" href="/vendor/jquery-ui/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href='/vendor/select2/dist/css/select2.min.css'>

<?php } else { ?>

    <link rel="stylesheet" type="text/css" href="/vendor/jquery-ui/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href='/vendor/select2/dist/css/select2.min.css'>

<?php } ?>

<link rel="stylesheet" type="text/css" media="screen" href="/css/style.css">