<?php if (!$this->config()->isDebug()) { ?>

    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/js/bootstrap.min.js'></script>
    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'></script>
    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js'></script>
    <script type="text/javascript" src='/vendor/select2/dist/js/select2.min.js'></script>
    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
    <script type="text/javascript" src="//cdn.ravenjs.com/1.1.18/jquery,native/raven.min.js"></script>

    <script>
        Raven.config("<?= $this->config('zend-sentry')['sentry-api-key-js'] ?>").install();

        <?php if($this->user()->hasIdentity()) { ?>
            Raven.setUserContext({
                name: "<?= $this->user()->currentUser()->getName() ?>",
                email: "<?= $this->user()->currentUser()->getEmail() ?>",
                id: <?= $this->user()->currentUser()->getId() ?>
            });
        <?php } ?>

    </script>

<?php } else { ?>

    <script type="text/javascript" src='/vendor/jquery/jquery-2.1.1.min.js'></script>
    <script type="text/javascript" src='/vendor/jquery-ui/jquery-ui.min.js'></script>
    <script type="text/javascript" src='/vendor/bootstrap/js/bootstrap.min.js'></script>
    <script type="text/javascript" src='/vendor/underscore/underscore-min.js'></script>
    <script type="text/javascript" src='/vendor/backbone/backbone-min.js'></script>
    <script type="text/javascript" src='/vendor/select2/dist/js/select2.min.js'></script>
    <script type="text/javascript" src='/vendor/momentjs/moment.js'></script>

<?php } ?>

<script type="text/javascript" src='/js/app.js'></script>