<div class="container-fluid pt15 pb15">

    <h2 class="light-grey mt10 mb0 narrow-spaced uppercase normal"><i class="fa fa-line-chart fa-2x"></i> Report</h2>

    <hr/>

    <div class="pl20 pr20" id="report-index">
        <div class="row">
            <div class="col-xs-12 col-sm-5">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-dashboard mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/overview">Overview</a></h3>
                        <p>
                            Menampilkan statistik dan analisa bisnis Anda secara garis besar.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-5 col-sm-push-1">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-bar-chart-o mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/cash-flow">Grafik Cash Flow</a></h3>
                        <p>
                            Menampilkan grafik perbandingan penjualan dan belanja dalam berbagai range waktu.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-5">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-money mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/sale/overview">Statistik Penjualan</a></h3>
                        <p>
                            Grafik penjualan dilihat dari berbagai sisi dan range waktu tertentu.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-5 col-sm-push-1">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-table mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/sale/table">Tabel Penjualan</a></h3>
                        <p>
                            Menampilkan tabel penjualan yang dapat di download dalam bentuk excel.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-5">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-truck mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/purchase/overview">Statistik Belanja</a></h3>
                        <p>
                            Grafik belanja dilihat dari berbagai sisi dan range waktu tertentu.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-5 col-sm-push-1">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-table mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/purchase/table">Tabel Belanja</a></h3>
                        <p>
                            Menampilkan tabel belanja yang dapat di download dalam bentuk excel.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-5">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-dot-circle-o mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/menu">Analisis Menu</a></h3>
                        <p>
                            Analisis perilaku konsumen dalam memilih produk.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-5 col-sm-push-1">
                <div class="row">
                    <div class="col-xs-4 text-right">
                        <i class="fa fa-5x fa-pie-chart mt20"></i>
                    </div>
                    <div class="col-xs-8">
                        <h3><a class="green" href="/reports/outlet/index">Analisis Outlet</a></h3>
                        <p>
                            Grafik, tren &amp; tabel penjualan di setiap outlet.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
