<?php

use Stokq\DTO\SaleWithTotal;
use Stokq\Entity\Account;
use Stokq\Entity\Outlet;
use Stokq\Entity\User;
use Stokq\Stdlib\FormUtil;

/** @var Account $account */
$account = $this->account;

/** @var User $user */
$user = $this->user;

/** @var Outlet[] $outlets */
$outlets = $this->outlets;

/** @var SaleWithTotal[] $pages */
$pages = $this->pages;

?>

<script>

    function deleteItem(target) {
        var self = $(target);
        if (confirm('Are you sure?')) {
            $.ajax({
                url: self.attr('href'),
                method: 'delete',
                success: function() {
                    self.closest('tr').fadeOut();
                },
                error: function() {
                    alert('Tidak dapat menghapus item yang dipilih, cobalah beberapa saat lagi.');
                }
            });
        }
        return false;
    }

</script>

<div class="container-fluid pt15 pb15">

    <button type="button" class="btn alt green mb20" data-toggle="modal" data-target="#select-outlet-modal">
        <i class="fa fa-plus"></i> Tambah Daftar Penjualan
    </button>

    <div class="inline-block middle mt-20">
        <a class="grey underscore smaller-text inline-block p5 pr0 pl15" href="/reports/sale/overview">Overview Penjualan</a>
        <a class="grey underscore smaller-text inline-block p5 pr0 pl15" href="/reports/outlet">Statistik Outlet</a>
        <a class="grey underscore smaller-text inline-block p5 pr0 pl15" href="/reports/cash-flow">Grafik Penjualan &amp; Belanja</a>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="row well green card alt-form ml0 mr0 pt5 pl0 pr0 pb10 mb0">
                <form action="">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Keyword</label>
                            <input type="text" name="q" value="<?= $this->keyword ?>" class="form-control" placeholder="Keyword">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Outlet</label>
                            <div class="block">
                                <select name="outlets[]" title="Outlet" multiple data-ui="select2" class="form-control">
                                    <?php foreach ($outlets as $outlet) { ?>
                                        <option value="<?= $outlet->getId() ?>" <?php if (is_array($this->selectedOutlets) &&
                                            in_array($outlet->getId(), $this->selectedOutlets)) { ?> selected <?php } ?>>
                                            <?= $outlet->getName() ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="control-label">Dari Tgl</label>
                            <input type="text" name="from" value="<?= $this->from ?>" class="form-control" placeholder="Dari Tgl" data-ui="datepicker">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="control-label">Sampai Tgl</label>
                            <input type="text" name="to" value="<?= $this->to ?>" class="form-control" placeholder="Sampai Tgl" data-ui="datepicker">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="control-label">&nbsp;</label>
                            <button type="submit" class="btn alt green uppercase form-control"> <i class="fa fa-search"></i> Cari </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="table-responsive pb50">
                <table class="table sales table-bordered table-hover dark-grey mt-1">
                    <thead>
                    <tr>
                        <th rowspan="2">#ID / Outlet</th>
                        <th rowspan="2" style="width: 200px;">Dibuat Oleh</th>
                        <th rowspan="2" style="width: 125px;">Tgl Order</th>
                        <th rowspan="2" style="width: 100px;">Jenis</th>
                        <th colspan="3">Penjualan</th>
                        <th rowspan="2" style="width: 60px;"></th>
                    </tr>
                    <tr>
                        <th>Item</th>
                        <th>Qty.</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody id="main-list" class="middle">
                    <?php if (count($pages)) { ?>
                        <?php foreach ($pages as $item) { ?>
                            <tr>
                                <td>
                                    <strong class="block">
                                        #<?= $item->getSaleId() ?>
                                        <?php if ($item->getSaleTitle()) { ?>
                                            : <?= $item->getSaleTitle() ?>
                                        <?php } ?>
                                    </strong>

                                    <?php if ($item->getOutletName()) { ?>
                                        <small class="grey block"><?= $item->getOutletName() ?></small>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?= $item->getCreatorName() ?>
                                    <small class="grey block"><?= $item->getCreatedAt()->format('M d, Y H:i') ?></small>
                                </td>
                                <td>
                                    <?= $item->getOrderedAt()->format('M d, Y') ?>
                                </td>
                                <td>
                                    <?= $item->getType() ?>
                                </td>
                                <td>
                                    <span class="green"><?= $item->getNumItems() ?></span>
                                </td>
                                <td>
                                    <span class="green"><?= $item->getNumQuantity() ?></span>
                                </td>
                                <td>
                                    <strong class="light-grey block"><?= $account->getDefaultCurrency() ?></strong>
                                    <span class="green block text-right">
                                        <?= number_format($item->getTotal(), 2) ?>
                                    </span>
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">action <span class="caret"></span></button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="/sale/edit?id=<?= $item->getSaleId() ?>">Detail/Edit</a></li>
                                            <li><a href="/sale/print?id=<?= $item->getSaleId() ?>">Print Slip</a></li>
                                            <li><a href="/sale/download-excel?id=<?= $item->getSaleId() ?>">Download Excel</a></li>
                                            <li><a href="/sale/delete?id=<?= $item->getSaleId() ?>" onclick="return deleteItem(this);">Delete</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <tr>
                            <td colspan="8">
                                <p class="grey mt10 pl10"><i class="fa fa-warning"></i> Tidak ada data penjualan.</p>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>

            <div class="pull-right">
                <?= $this->pagination($pages) ?>
            </div>

        </div>
    </div>

</div>

<div class="modal" tabindex="-1" role="dialog" aria-hidden="true" id="select-outlet-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title uppercase smaller-text">Pilih Outlet</h4>
            </div>
            <form action="/sale/new" method="get" class="form alt-form bigger-label">
                <div class="modal-body bg-grey">
                    <div class="control-group">
                        <select class="form-control" name="id" title="Pilih Outlet">
                            <?php foreach ($outlets as $outlet) { ?>
                                <option value="<?= $outlet->getId() ?>"><?= $outlet->getName() ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    <button type="submit" class="btn alt green">Lanjutkan <i class="fa fa-mail-forward"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>