<?php

use Stokq\Entity\Account;
use Stokq\Entity\MenuPrice;
use Stokq\Entity\Outlet;
use Stokq\Entity\User;

/** @var Account $account */
$account = $this->account;

/** @var User $user */
$user = $this->user;

/** @var Outlet $outlet */
$outlet = $this->outlet;

/** @var MenuPrice[] $items */
$items = $this->items;

?>

<script type="text/javascript" src="/vendor/jquery-mask/jquery.mask.min.js"></script>
<script type="text/javascript" src="/vendor/accounting.js/accounting.min.js"></script>
<script>
    var createSaleForm,
        saveBtn;

    function computeSubtotal() {
        $('[data-quantity], [data-price]').on('keyup change', function() {
            var target = $(this),
                tr = target.closest('tr'),
                price = tr.find('[data-price]'),
                qty = tr.find('[data-quantity]'),
                subtotal = accounting.unformat(qty.val()) * accounting.unformat(price.val());

            $('[data-subtotal]', tr).val(accounting.formatNumber(subtotal, 0)).trigger('change');
            $('[data-total]', tr).val(accounting.formatNumber(subtotal, 0)).trigger('change');
        });
    }

    function computeTotalSummary() {
        var totalData = $('[data-total]'),
            subtotalData = $('[data-subtotal]'),
            total = 0,
            subtotal = 0;

        totalData.each(function(k, v) {
            var node = $(v),
                val = parseFloat(accounting.unformat(node.val()));
            if (!isNaN(val) && (val > 0)) {
                total += val;
            }
        });
        $('[data-total-summary]').val(accounting.formatNumber(total, 0));

        subtotalData.each(function(k, v) {
            var node = $(v),
                val = parseFloat(accounting.unformat(node.val()));
            if (!isNaN(val) && (val > 0)) {
                subtotal += val;
            }
        });
        $('[data-subtotal-summary]').val(accounting.formatNumber(subtotal, 0));
    }

    $(document).ready(function () {

        saveBtn = $('#save-btn');
        createSaleForm = $('#create-sale-form');

        ajaxForm(createSaleForm, {
            before: function() {
                var total = parseFloat(accounting.formatNumber($('[data-total-summary]').val()));
                if (total <= 0) {
                    alert('Total amount is empty.');
                    return false;
                }
                return true;
            },
            ok: function(data, status) {
                if (status == 'success') {
                    alert('Data berhasil ditambahkan, klik OK untuk kembali ke daftar belanja.');
                    window.location.href = '/sale';
                }
            },
            busy: function() {
                saveBtn.attr('disabled', 'disabled');
                $('span', saveBtn).text('Menyimpan data...');
            },
            done: function() {
                saveBtn.removeAttr('disabled');
                $('span', saveBtn).text('Simpan');
            }
        });

        $('[data-subtotal]').on('keyup change', function() { computeTotalSummary(); });
        $('[data-total]').on('keyup change', function() { computeTotalSummary(); });

        computeSubtotal();

        $('[data-total], [data-subtotal], [data-price]').mask("#,##0", {reverse: true});
    });
</script>

<form action="/sale/create" method="post" class="form alt-form" id="create-sale-form">
    <div class="container-fluid pt5 pb20 pl20 pr20 bg-grey bb1s">
        <h3 class="dark-grey mb0 pb0">
            Tambah Daftar Penjualan
        </h3>
        <small>Bahan makanan akan dikurangkan di gudang dari outlet &lsquo;<?= $outlet->getName() ?>&rsquo;.</small>
    </div>

    <div class="container-fluid pt5 pb20 pl20 pr20 bg-light-yellow bb1s">
        <div class="row form-alt">
            <div class="col-sm-10">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label">Judul</label>
                            <input type="text" name="title" value="" class="form-control" placeholder="Judul">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="control-label">Jenis</label>
                            <select name="type" class="form-control" title="Jenis">
                                <option value="recap">Rekap</option>
                                <option value="order">Order</option>
                                <option value="other">Lainnya</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="control-label">Tgl Order</label>
                            <input type="text" name="ordered_at" value="<?= date('M d, Y') ?>" class="form-control" placeholder="Tgl Order" data-ui="datepicker" data-format="M dd, yy">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label">Outlet</label>
                            <input type="text" value="<?= $outlet->getName() ?>" class="form-control" placeholder="Outlet" disabled>
                            <input name="outlet" type="hidden" value="<?= $outlet->getId() ?>"/>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label class="control-label">Dibuat Oleh</label>
                            <input type="text" value="<?= $user->getName() ?>" class="form-control" placeholder="" disabled/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid p20">
        <div class="row">
            <div class="col-sm-12">

                <div class="table-responsive" style="overflow-y: hidden;">
                    <h4 class="alt-heading-4">Item Penjualan</h4>

                    <div class="raw-items-errors">
                        <div data-error-for="raw_items"></div>
                    </div>

                    <table class="table table-bordered p6 sale-items mt20">
                        <thead>
                        <tr>
                            <th style="width: 35%;">Item</th>
                            <th style="width: 15%;">Harga/Unit</th>
                            <th style="width: 10%;">Qty</th>
                            <th style="width: 20%;">Subtotal</th>
                            <th style="width: 20%;">Total</th>
                        </tr>
                        </thead>
                        <tbody id="sale-item-rows">
                        <?php foreach ($items as $key => $item) { ?>
                            <tr>
                                <td>
                                    <input type="text" name="raw_items[<?= $key ?>][item_name]"
                                           value="<?= $item->getMenu()->getName() ?>" class="alt form-control" placeholder="" readonly/>
                                    <input name="raw_items[<?= $key ?>][menu_price]" type="hidden"
                                           value="<?= $item->getId() ?>">
                                </td>
                                <td>
                                    <input type="text" name="raw_items[<?= $key ?>][unit_price]" data-price
                                           value="<?= (int)$item->getPrice() ?>" class="alt form-control" placeholder=""/>
                                </td>
                                <td>
                                    <input type="number" name="raw_items[<?= $key ?>][quantity]" data-quantity
                                           value="0" class="alt form-control" placeholder="" step="0.5" min="0"/>
                                </td>
                                <td>
                                    <input type="text" name="raw_items[<?= $key ?>][subtotal]" data-subtotal
                                           value="0" class="alt form-control" placeholder="" readonly/>
                                </td>
                                <td>
                                    <input type="text" name="raw_items[<?= $key ?>][total]" data-total
                                           value="0" class="alt form-control" placeholder=""/>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="3" class="text-right grey uppercase middle"><strong>Total</strong></td>
                            <td class="text-right">
                                <input class="alt form-control text-right" type="text" disabled value="0" placeholder="" data-subtotal-summary />
                            </td>
                            <td class="text-right">
                                <input class="alt form-control text-right" type="text" disabled value="0" placeholder="" data-total-summary />
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>

        </div>
    </div>

    <div class="container-fluid pt5 pb20 pl20 pr20 bg-grey bt1s">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label">Catatan</label>
                    <textarea name="note" rows="4" class="form-control" placeholder="Catatan"></textarea>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="update_stock_level" checked>
                        Centang untuk update level stok di gudang.
                    </label>
                </div>
                <button type="submit" class="btn alt green mt20" id="save-btn"><i class="fa fa-save"></i> <span>Simpan</span></button>
            </div>
        </div>
    </div>

    <input name="currency" type="hidden" value="<?= $account->getDefaultCurrency() ?>"/>
</form>