<?php

use Stokq\Entity\Account;
use Stokq\Entity\MenuSale;
use Stokq\Entity\OutletSale;
use Stokq\Entity\Sale;
use Stokq\Entity\User;

/** @var Sale $sale */
$sale = $this->sale;

/** @var Account $account */
$account = $this->account;

/** @var number $total */
$total = 0;

/** @var number $subtotal */
$subtotal = 0;

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $sale->getTitle() ?></title>
    <?php if (!$this->config()->isDebug()) { ?>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css">
    <?php } else { ?>
        <link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/bootstrap.min.css">
    <?php } ?>

    <style type="text/css">
        body {
            padding-bottom: 50px;
        }

        .text-right {
            text-align: right;
        }

        .left {
            float: left;
        }

        .grey {
            color: #999;
        }

        .customer p, .supplier p {
            margin-bottom: 5px;
        }

    </style>

    <style type="text/css" media="print">
        body {
            font-size: 11px;
        }
    </style>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1><?= $sale->getTitle() ?></h1>

            <?php if ($sale->getOrderedAt()) { ?>
                <h4>Tanggal: <?= $sale->getOrderedAt()->format('d M Y') ?></h4>
            <?php } ?>

            <hr/>

        </div>
    </div>
    <div class="row">
        <div class="col-xs-5 customer">
            <h4><?= $account->getName() ?></h4>

            <?php if ($account->getAddress()) { ?>
                <p><?= $account->getAddress() ?></p>
            <?php } ?>

            <?php if ($account->getPhone()) { ?>
                <p><?= $account->getPhone() ?></p>
            <?php } ?>

            <?php if ($account->getEmail()) { ?>
                <p><?= $account->getEmail() ?></p>
            <?php } ?>

            <?php if ($account->getWebsite()) { ?>
                <p><?= $account->getWebsite() ?></p>
            <?php } ?>

        </div>
    </div>

    <br/>
    <br/>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Item</th>
            <th>Harga / Unit</th>
            <th>Qty.</th>
            <th>Unit</th>
            <th>Subtotal</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($sale->getItems() as $item) { ?>
            <tr>
                <td>
                    <?= $item->getItemName() ?>
                </td>
                <td class="text-right">
                    <small class="left grey"><?= $account->getDefaultCurrency() ?></small>
                    <?= number_format($item->getUnitPrice(), 2) ?>
                </td>
                <td>
                    <?= $item->getQuantity() ?>
                </td>
                <td>
                    <?php if ($item->getMenuSale() instanceof MenuSale) { ?>
                        <?= $item->getMenuSale()->getMenuPrice()->getMenu()->getServingUnit() ?>
                    <?php } ?>
                </td>
                <td class="text-right">
                    <small class="left grey"><?= $account->getDefaultCurrency() ?></small>
                    <?= number_format($item->getSubtotal(), 2) ?>
                </td>
                <td class="text-right">
                    <small class="left grey"><?= $account->getDefaultCurrency() ?></small>
                    <?= number_format($item->getTotal(), 2) ?>
                </td>
            </tr>
            <?php

            $subtotal += (float)$item->getSubtotal();
            $total += (float)$item->getTotal();

            ?>
        <?php } ?>
        </tbody>
        <tfoot>
        <tr>
            <th class="text-right" colspan="4">
                <h4>Total</h4>
            </th>
            <td class="text-right">
                <small class="left grey"><?= $account->getDefaultCurrency() ?></small>
                <?= number_format($subtotal, 2) ?>
            </td>
            <td class="text-right">
                <small class="left grey"><?= $account->getDefaultCurrency() ?></small>
                <?= number_format($total, 2) ?>
            </td>
        </tr>
        </tfoot>
    </table>

    <br/>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Dibuat Oleh</th>
            <th>Dari Outlet</th>
            <th>Tgl. Dibuat</th>
            <th>Tgl. Order</th>
            <th>Tgl. Dicetak</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php if ($sale->getCreator() instanceof User) { ?>
                    <?= $sale->getCreator()->getName() ?>
                <?php } else { ?>
                    -
                <?php } ?>
            </td>
            <td>
                <?php if ($sale->getOutletSale() instanceof OutletSale) { ?>
                    <?= $sale->getOutletSale()->getOutlet()->getName() ?>
                <?php } else { ?>
                    -
                <?php } ?>
            </td>
            <td>
                <?= $sale->getCreatedAt()->format('d M Y') ?>
            </td>
            <td>
                <?php if ($sale->getOrderedAt()) { ?>
                    <?= $sale->getOrderedAt()->format('d M Y') ?>
                <?php } else { ?>
                    -
                <?php } ?>
            </td>
            <td>
                <?= date('d M Y') ?>
            </td>
        </tr>
        </tbody>
    </table>

    <div class="row">
        <div class="col-xs-6">
            <h4>Catatan</h4>
            <p>
                <?php if ($sale->getNote()) { ?>
                    <?= $sale->getNote() ?>
                <?php } else { ?>
                    <em class="grey">Tidak ada catatan untuk pembelian ini</em>
                <?php } ?>
            </p>
        </div>
    </div>

</div>


<script type="text/javascript">
    window.print();
</script>

</body>
</html>